### ISSUE TITLE
Added Sphere Coordinates

### ISSUE THREAD

**Issue by haldunbalim** [CMM-22/a2#11]
For the task 5 I added a sphere to the world but I don't think there is a function to get its' coordinates. So, to walk over it I assumed the center and radius of the sphere is known by the controller. Is it okay or should we develop an adaptive controller? If not, how can we get the coordinates of the added objects?

**Comment by eastskykang** [comment]
You can assume that the terrain is known to the controller. I believe computing a point's (x, y, z) coordinate of spherical terrain should be straight forward. There is an analytic expression.

**Comment by haldunbalim** [comment]
Thanks
