### ISSUE TITLE
Test of Jacobian

### ISSUE THREAD

**Issue by AnqiaoLi** [CMM-22/a2#13]
In assignment 2, the following two functions seem only used to follow the foot trajectory, thus the `rb` is always the shank of the robot. Do we need to consider more general cases, like calculating the Jacobian with respect to points on other links of the robot? And in test-a2.app and further tests after the deadline, will these general cases be tested? 

`void estimate_linear_jacobian(const P3D &p, RB *rb, Matrix &dpdq)
`
`void compute_dpdq(const P3D &p, RB *rb, Matrix &dpdq)`

**Comment by eastskykang** [comment]
As you mentioned, ```RB *rb``` specifies the local coordinate frame where ```P3D &p``` is expressed in. 

You don't have to consider the case where ```p``` is expressed in different local coordinate system than ```RB *rb```'s coordinate frame.

**Comment by eastskykang** [comment]
Yes. Jacobian functions should return the correct Jacobian matrix regardless the ```p``` and ```rb```.

**Comment by AnqiaoLi** [comment]
Okay, thanks.
