### ISSUE TITLE
Definition of base orientation angles in general coordinate vector

### ISSUE THREAD

**Issue by spolinski** [CMM-22/a2#14]
How are the angles defined in the general coordinate vector? Intuitively it would make sense for it to be in the order x-y-z, since the position is also defined in the order x-y-z:
q(3) = euler_x
q(4) = euler_y
q(5) = euler_z

However, in the Tutorial slides, Theta is defined as [psi, theta, phi] which would correspond to:
q(3) = psi = euler_y
q(4) = theta = euler_x
q(5) = phi = euler_z

Since the rotation is YXZ I believe it is the second one, but I just want to make sure. Could you please clarify this? Thanks!
<img width="855" alt="image" src="https://user-images.githubusercontent.com/91253120/159977914-57248e31-51e0-43d7-8d8f-4e13de9df748.png">

**Comment by eastskykang** [comment]
Please see relevant issue #10
