### ISSUE TITLE
Ex1: Program immediately closes

### ISSUE THREAD

**Issue by kiremicev** [CMM-22/a2#17]
I cannot figure out the program immediately closes after starting it.
![grafik](https://user-images.githubusercontent.com/100943022/160115726-c43f364b-f6b1-49ad-b9f9-83766dd7bfac.png)
Did I do something wrong in the code maybe?
Thank you for your help!

**Comment by kiremicev** [comment]
I found the problem. I just had to change qIndex >= 6 instead of >2 in the for loop.

**Comment by eastskykang** [comment]
@kiremicev you can use **Debug** mode and a **debugger** to identify the line where segmentation fault happens. Please see #2.
