### ISSUE TITLE
Slow FPS

### ISSUE THREAD

**Issue by Marialenakdg** [CMM-22/a2#25]
My FPS is 15 and my dog moves slowly. Is this a problem of my implementation? 

Thank you!

**Comment by eastskykang** [comment]
are you building your code in cmake Release mode?

**Comment by Marialenakdg** [comment]
Thank you very much for your answer. Yes I running it in the Release mode which provides me the same FPS with the debug mode, namely 15

**Comment by Marialenakdg** [comment]
I don't know why but now it runs with FPS 30. I checked it before to build it in cmake but maybe it wasn't. 

Thank you!
