### ISSUE TITLE
Repo not under CMM-22

### ISSUE THREAD

**Issue by joshuaoreilly** [CMM-22/a2#26]
For a0 and a1, my repo was under `CMM-22/a0-joshuaoreilly` and `CMM-22/a1-joshuaoreilly`. For a2, however, I noticed that Github put the repo under `joshuaoreilly/a2-joshuaoreilly`. I don't think I did anything differently than last time; I clicked *Use this template*, and it created it under me instead of CMM-22. I've tried copying all branches and setting it to both public and private when using the template, and also tried forking, but for whatever reason, the project isn't under CMM-22. How can I fix this?

**Comment by eastskykang** [comment]
@joshuaoreilly can you click this link here again?: https://classroom.github.com/a/-ar_SEpg

Please let me know if it gives you an error.

**Comment by joshuaoreilly** [comment]
That worked, I completely forgot we had to follow the Github classroom invite. Thanks!
