### ISSUE TITLE
Laggy video for Ex 5

### ISSUE THREAD

**Issue by azurite** [CMM-22/a2#28]
I have recorded a screen capture of my robot walking on uneven terrain for the Ex 5 task. 

However probably due to my laptop not having a very strong cpu the video is lagging sometimes even though one can still clearly see the robot walking along the uneven terrain.

Is that ok for a video submission?

**Comment by eastskykang** [comment]
Can you give me your video URL here?

**Comment by azurite** [comment]
I tried both cases (cap fps to 30 and uncapped) and the occasional lagging still persists. When I screen capture with capped to 30 fps the fps occasionally drops to like ~27 that why I unticked the box to see if this would fix it but in the end it looks like the lagging is here in both cases.

**Comment by azurite** [comment]
I recorded it again on my windows machine with fps limited to 30 and the lag seems to be gone now. I've updated the video link.
