### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by Snowmanda** [CMM-22/a2#30]
Hi,

When i tried to push my work it threw me this error:
remote: Permission to CMM-22/a2.git denied to Snowmanda.
fatal: unable to access 'https://github.com/CMM-22/a2.git/': The requested URL returned error: 403

commit worked without a problem.

Can someone help me out?

Thanks a lot.

**Comment by eastskykang** [comment]
You are trying to push your code to template repo. You should push your code to your own repo.

Please consult me in today's tutorial session if this blocks you.

**Comment by eastskykang** [comment]
Okay I'm closing this issue. Please let me know if you have a further request :)
