### ISSUE TITLE
Ex2 Robots bases snaps lower at start of animation. Is this intended?

### ISSUE THREAD

**Issue by davzzar** [CMM-22/a2#31]
I have implemented an IK solver which seems to work. But on second viewing I found that the walking cycle is a bit off from that which is shown in the readme. Namely, the robot seems to be "crouching" more - the base is lower in the y direction. See the screenshot comparison below.

I am assuming this is not intended, and I have a bug. Is this so? Do I need to invest more time into this?

REFERENCE:
![image](https://user-images.githubusercontent.com/7673161/161061406-618bcd61-5c3c-4a4d-beed-10bce6cffa79.png)

MINE:
![image](https://user-images.githubusercontent.com/7673161/161061448-e460e414-a13f-4b3a-bd58-dba76620bf6c.png)

**Comment by davzzar** [comment]
Specifically, on initialization, the robot looks like so:
![image](https://user-images.githubusercontent.com/7673161/161062413-1f8e2417-2593-48bc-b930-37657979b76a.png)

One frame into the animation, we have:
![image](https://user-images.githubusercontent.com/7673161/161062513-8005da17-b4de-4666-bfb4-79664093d465.png)

My assumption is that I am moving the base to it's COM?

**Comment by davzzar** [comment]
And the same without mesh rendering:

![image](https://user-images.githubusercontent.com/7673161/161063254-89bc521a-a6ba-476a-b282-ef2fe1ddf9c9.png)

![image](https://user-images.githubusercontent.com/7673161/161063327-4506d250-d252-46de-8d9f-7efee0d8ed5e.png)

**Comment by Sibsoon** [comment]
As from what I found in the code it is intentional, since the start position is defined somewhere in the robot configuration, where the position during animation is defined by the groundHeight and the trunk height.

**Comment by davzzar** [comment]
Awesome! I assumed that I was accidentally updating the base position unknowingly. Moving right along.
