### ISSUE TITLE
Unable to enter the assignment repository

### ISSUE THREAD

**Issue by TonyStone191031** [CMM-22/a2#4]
I have accepted the assignment a2 and the assignment repository has been created, however, I cannot visit the repository and it showed that "Page not found" (I have logged into my GitHub account on the browser). How can it be fixed?

![2](https://user-images.githubusercontent.com/57191316/158888990-93e8ea6b-64ef-4afc-a11b-929cd62ff55b.png)
![1](https://user-images.githubusercontent.com/57191316/158888995-248d7e9a-4d26-471b-9406-a0d26911cb93.png)

**Comment by eliafranc** [comment]
Have the exact same problem.

**Comment by eastskykang** [comment]
@TonyStone191031 @eliafranc Please try it again and let me know if it still doesn't work.

**Comment by eliafranc** [comment]
@eastskykang It worked for me now. Thank you!

**Comment by TonyStone191031** [comment]
@eastskykang It still doesn’t work for me. The repository link is still invalid.

**Comment by eastskykang** [comment]
@TonyStone191031 this is bizarre. I tried to create repository manually but it says the repo already exists although I cannot see it. I think GitHub classroom malfunctioned. 

Please leave your eth mail here. I will send you the code with a zip file. Meantime, I will contact GitHub to figure what causes the problem.

**Comment by TonyStone191031** [comment]
@eastskykang Thanks! My mail is zhuofanshi@student.ethz.ch

**Comment by eastskykang** [comment]
@TonyStone191031 code files are sent.

**Comment by eastskykang** [comment]
@TonyStone191031 update: I've got an update from GitHub team. I will let you know once it's settled. Meantime, please keep use github private repo to save your code. Just please make sure your repo is private so that no other student can see it. 

Once your repo under cmm22 classroom is ready, you can migrate your code into the new repo.
