### ISSUE TITLE
building problem

### ISSUE THREAD

**Issue by Sedrin** [CMM-22/a2#6]
Without changing anything in the files I tried to set up problem a2 in vs studio and the build step exit with code 1. The following errors occur:

<img width="872" alt="a2_error" src="https://user-images.githubusercontent.com/100570059/159115344-8d0ca290-a45d-45db-b346-66107ed3042c.png">

I am a bit confused because the building procedure worked for problem a0 and a1.

**Comment by eastskykang** [comment]
It could be the case that your project directory path overflows. 

Please try to move your project directory to desktop, and remove build directory and build it again.

**Comment by Sedrin** [comment]
It works! Thanks!
