### ISSUE TITLE
running locomotion

### ISSUE THREAD

**Issue by samibouziri** [CMM-22/a2#7]
Hello,

eventhough when building don't get any error, i cannot run locomotion app and i get this message 
![Capture](https://user-images.githubusercontent.com/79418773/159118942-53eee36b-2f4b-4dde-a5bc-b75868e06caf.PNG)
I wanted to know if there was a way to resolve that

Thanks.

**Comment by eastskykang** [comment]
Hi,

I need more information to identify the problem. Can you run your code on VS Code with a debugger? You should build the code in Debug mode to run debugger. 

Once you run debugger, it will break (stop) at the point where the segmentation fault happens.

**Comment by samibouziri** [comment]
I figured out the problem. I wanted to access the content of a NULL object.

**Comment by eastskykang** [comment]
Great! I am closing this issue now.
