### ISSUE TITLE
Very slow visualization

### ISSUE THREAD

**Issue by alemercurio** [CMM-22/a2#9]
Hello, I have completed up to part 2 of the assignment, and my robot is trotting in place in the visualization tool.

The problem is that it is doing so at a very very low speed. In the visualization tool it says it is running at 3 FPS. If I change the solving steps from 10 to 2, for example, it gets a little better, but still slower than the video showed.

Is this only because I do not have a dedicated GPU in my laptop or it is possible that my solution is somehow wrong? I have a DELL XPS-13 with intelCore i7 and 16 GB of RAM, but no dedicated GPU, and I am on Ubuntu native boot (dual boot setup).

Thank you!

**Comment by eastskykang** [comment]
Hi @alemercurio are you building code in CMake Release mode? I think your machine is powerful enough to run the code in real-time.

**Comment by alemercurio** [comment]
I was in Debug mode. That solved the problem. Thank you very much!
